code review for use of filenames with quotes, slashes and multiple spaces standardize function argument reception use exit code 2 for bad usage

diff --git a/undvd b/undvd
--- a/undvd
+++ b/undvd
@@ -72,9 +72,9 @@ done
 
 if [[ ! -e "$dvd_device" ]]; then
 	echo -e "${wa}=>${r} The dvd device ${bb}$dvd_device${r} does not exist."
-	echo -e "${wa}=>${r} Supply the right dvd device to $(basename $0), eg:"
-	echo -e "    ${b}$(basename $0) -d ${bb}${dvd_device}${r} [${b}other options${r}]"
-	exit 1
+	echo -e "${wa}=>${r} Supply the right dvd device to ${tool_name}, eg:"
+	echo -e "    ${b}${tool_name} -d ${bb}${dvd_device}${r} [${b}other options${r}]"
+	exit 2
 fi
 
 if [[ "$opt_noclone" ]]; then
@@ -91,13 +91,13 @@ fi
 if [[ ! "$titles" ]]; then
 	echo -e "${e}No titles to rip, exiting${r}"
 	echo -e "$usage"
-	exit 1
+	exit 2
 fi
 
 if [[ ! "$alang" ]]; then
 	echo -e "${e}No audio language selected, exiting${r}"
 	echo -e "$usage"
-	exit 1
+	exit 2
 else
 	audio=$(ternary_int_str "$alang" "-aid" "-alang")
 fi
@@ -111,7 +111,7 @@ fi
 
 $mkdir -p logs
 if [[ $? != 0 ]] ; then
-	echo -e "${e}Could not write to $PWD, exiting${r}"
+	echo -e "${e}Could not write to ${bb}$PWD${e}, exiting${r}"
 	exit 1
 fi
 
diff --git a/vidstat b/vidstat
--- a/vidstat
+++ b/vidstat
@@ -31,7 +31,7 @@ done
 
 if [[ ! "$input_dvd_device" && ! "$@" ]]; then
 	echo -e "$usage"
-	exit 1
+	exit 2
 fi
 
 
@@ -46,7 +46,7 @@ if [[ "$input_dvd_device" ]]; then
 			i=$(( $i+1 ))
 		done
 	else
-		echo -e "${e}Could not read from ${it}$input_dvd_device${e} dvd device${r}"
+		echo -e "${e}Could not read from ${bb}$input_dvd_device${e} dvd device${r}"
 		exit 1
 	fi
 else
@@ -60,7 +60,7 @@ fi
 display_title_line "\"header\""
 for file in "${files[@]}"; do
 	if [[ ! "$input_dvd_device" && ! -e "$file" ]]; then
-		echo -e "${e}File $file does not exist"
+		echo -e "${e}File ${bb}$file${e} does not exist"
 		exit 1
 	fi
 
