add exit for non-existent dvd device

diff --git a/undvd b/undvd
--- a/undvd
+++ b/undvd
@@ -67,6 +67,7 @@ if [ ! -e "$dvd_device" ]; then
 	echo -e "${wa}=>${r} The dvd device ${bb}$dvd_device${r} does not exist."
 	echo -e "${wa}=>${r} Supply the right dvd device to $(basename $0), eg:"
 	echo -e "    ${b}$(basename $0) -d ${bb}${dvd_device}${r} [${b}other options${r}]"
+	exit 1
 fi
 
 if [ "$opt_noclone" ]; then
@@ -159,7 +160,7 @@ for title in $titles; do
 		height=${info[1]}
 		crop_filter="crop=${info[2]},"
 		if [[ ! "$width" || ! "$height" || ! "$crop_filter" ]]; then
-			echo -e "${e}Crop detection failed${r}         "
+			echo -e "${e}Crop detection failed${r}              "
 			exit 1
 		fi
 	fi
